name: push

on:
  push:
    branches-ignore:
      - 'refs/tags/v'

jobs:
  checks:
    uses: openweathermap/deker-actions/.github/workflows/checks.yml@master
    permissions:
      - secrets: read
    with:
      python-version: '3.9'
      min-coverage: 60
    secrets: ${{ secrets.PACKAGE_NAME }}
