name: test-build

on:
  push:
    tags-ignore:
      - 'v[1-9]+.[0-9]+.[0-9]+'

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build sdist
        run: |
          pip install poetry-dynamic-versioning
          pip install poetry
          poetry dynamic-versioning enable
          poetry build -f sdist

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

  upload_test_pypi:
    needs: build_sdist
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: testpypi
      url: https://test.pypi.org/p/deker-shell

    steps:
      - uses: actions/download-artifact@v3
        with:
          # unpacks default artifact into dist/
          # if `name: artifact` is omitted, the action will create extra parent dir
          name: artifact
          path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
